### ISSUE TITLE
poor embeddings with flair 

### ISSUE THREAD

**Issue by leandadearaujo** [derlem/kanarya#14]
i tried to stack  elmo , bert , word , flair embeddings using  document embedding and tried to find the cosine similarity between two sentences after embedding the sentences  i get really very bad rcosine similarity score  

why so ???

Please help me resolve 

where am i going wrong ?
is there any better way/library to approach this prob
 Infact  I get better result if i use word embeddings (glove ) only

**Comment by ugurcanarikan** [comment]
I think you should be asking this question to [flair](https://github.com/zalandoresearch/flair/) as they are the ones who implemented stacked embeddings but the fact that cosine similarity drops when you use stacked embeddings doesn't necessarily mean you are doing something wrong as when you stack different embeddings, you are actually concatenating them together.

**Comment by leandadearaujo** [comment]
Yes I will surely ask them



Thank you so much for your response and knowledge

Regards
Leanda
