### ISSUE TITLE
Run BERT pretraining on TRUBA

### ISSUE THREAD

**Issue by haozturk** [derlem/kanarya#18]
We have run BERT pretraining on our machines with small number of training steps successfully. Now it is time to run it on a more powerful grid, TRUBA, to get a much more effective result. All the data required for BERT pretraining is ready.

**Comment by haozturk** [comment]
I have started the transfer of `tfrecords` needed for BERT pretraining from `Minerva` to `TRUBA`. The records are about 150 GB, it will take some time. Therefore status is currently blocked.

**Comment by onurgu** [comment]
I think we can also close this issue, did we follow up on this issue? I haven't heard about this for a while? @haozturk

**Comment by onurgu** [comment]
gereksizleşti. kapatıyorum.
