### ISSUE TITLE
Development of front-end for web application

### ISSUE THREAD

**Issue by haozturk** [derlem/kanarya#22]
We can track the status of frontend of our web application in this thread

**Comment by alperen-degirmenci-2017400255** [comment]
Current status of the web application is as following: 

Classifier model is loaded to the web application, at the beginning of running program. Outputs can be seen at the console, not on browser unfortunately. To-do's are:

- [ ] Showing the output at browser.
- [ ] Adding a back button on the result page.

**Comment by haozturk** [comment]
I have a suggestion for showing the error: We can highlight the incorrect word or words rather than showing a `<B-ERR>` tag. It is much more intuitive for a user. Of course this is a low priority suggestion. We can look at this after resolving the current issues.

**Comment by onurgu** [comment]
I think we can close this now, right? ;)
